     apiVersion: networking.k8s.io/v1
     kind: Ingress
     metadata:
      name: app2
      namespace: app2
     spec:
      ingressClassName: f5
      rules:
        - host: app2.k3s.net
          http:
            paths:
              - backend:
                  service:
                    name: app2
                    port:
                      number: 80
                pathType: Prefix
                path: /
