apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: f5devcentral/f5-demo-httpd:latest
          ports:
            - containerPort: 80
          env:
            - name: F5DEMO_APP
              value: "website"
            - name: F5DEMO_NODENAME
              value: "k3s App 2 Site A"
            - name: F5DEMO_COLOR
              value: "ccee00"
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: app2
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: 30102
  type: NodePort
  selector:
    app: app2
