apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: app1
  labels:
    f5cr: "true"
spec:
  domainName: app1.k3s.net
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: "/Common/LtmDcA"
    monitor:
      type: http
      send: "GET / HTTP/1.1\r\nHost: app1.k3s.net\r\n\r\n"
      recv: "200"
      interval: 3
      timeout: 10
