apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: f5devcentral/f5-demo-httpd:latest
          ports:
            - containerPort: 80
          env:
            - name: F5DEMO_APP
              value: "website"
            - name: F5DEMO_NODENAME
              value: "k3s App 1 Site B"
            - name: F5DEMO_COLOR
              value: "f56f42"
---
apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: app1
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: 30101
  type: NodePort
  selector:
    app: app1
